### ISSUE TITLE
0.14x Installation

### ISSUE THREAD

**Issue by bringking** [Kong/kong-plugin-proxy-cache#21]
Does this plugin work on Kong 0.14 Community edition? I tried adding it, and it doesn't seem included by default. Then I added it manually like our other custom plugins and it seems to fail with
```
kong-admin_1          | 2020/03/16 19:28:00 [error] 9#0: init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:136: attempt to call local 'handler' (a table value)
kong-admin_1          | stack traceback:
kong-admin_1          | 	/usr/local/share/lua/5.1/kong/init.lua:136: in function 'load_plugins'
kong-admin_1          | 	/usr/local/share/lua/5.1/kong/init.lua:204: in function 'init'
kong-admin_1          | 	init_by_lua:3: in main chunk
```
Is there a path to getting this working on 0.14?

**Comment by hishamhm** [comment]
@bringking It does not, sorry. We recommend upgrading Kong — you can upgrade 0.14 to 1.5.0, which includes `kong migrations migrate-apis` specifically for migrating from 0.14 into newer releases!

Once you upgraded to 1.5.0 and your 0.x data was carried over, you can then migrate to Kong 2.x :)
