### ISSUE TITLE
X-Cache-Status always showing Bypass

### ISSUE THREAD

**Issue by tanmoyrsc** [Kong/kong-plugin-proxy-cache#26]
Hi,

I have used this plugin with Kong (2.0.4) Community edition but X-Cache-Status is always Bypass. have set this proxy-caching using below command for all consumers. Please help me to sort this out.

curl -X POST http://xxx.xxx.xxx.xxx:8001/services/test-proxy-cache/plugins \
--data "name=proxy-cache"  \
--data "config.cache_ttl=300" \
--data "config.strategy=memory" \
--data "config.content_type=text/plain; charset=utf-8"
	
curl -X POST http://xxx.xxx.xxx.xxx:8001/routes/test-proxy-cache-route/plugins \
--data "name=proxy-cache"  \
--data "config.cache_ttl=300" \
--data "config.strategy=memory" \
--data "config.content_type=text/plain; charset=utf-8"  

Br,
Tanmoy

**Comment by gszr** [comment]
Hey @tanmoyrsc, could you share with us the headers your upstream service is responding with?

**Comment by locao** [comment]
Hi @tanmoyrsc, can you still reproduce this issue? Have you tried with the most recent Kong release?

**Comment by gszr** [comment]
Also, verify that the content-type returned by the upstream service exactly matches one of the values in `content_type`

**Comment by locao** [comment]
Closing this issue as we didn't receive updates. Please feel free to reopen it if the problem happens again.
